### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by miya0001** [mirucon/handbook-tracker#4]
これも好みかもですが、海外のWordPressコミュニティの人にも使ってもらうならコーディングスタンダードにマッチさせたほうがいいかなと思ったのですが、`prettier` に怒られちゃいますね。

特にこだわりがあるわけではないので、どっちにしろ適当に閉じてもらって大丈夫です。

**Comment by mirucon** [comment]
とりあえず今のところは Prettier でいく予定です、Prettier もしくは Standard に慣れてしまったので今更セミコロンとか書けないしめんどくさいので…
